version: '3'
services:
  dq-runner:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    image: dq-runner:latest
    volumes:
      - ./:/app
    environment:
      - ENV=local
      - PYTHONPATH=/app
    # This allows the container to see your Mac's MinIO on port 9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: tail -f /dev/null # Keep alive for Airflow to exec into
